INSERT INTO questions
    (id, track, difficulty, topic, prompt, question_type, coding_language, starter_code, function_signature,
     hidden_test_cases, created_at, updated_at)
VALUES
('70000000-0000-0000-0000-000000000001', 'DSA', 'EASY', 'Arrays',
 'Given an array of integers, find the maximum value in one pass.',
 'CODING', 'Java', 'class Solution { public int solve(int[] values) { return 0; } }',
 'int solve(int[] values)', '{"cases": [{"input": "[3,1,4]", "output": "4"}]}',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000002', 'DSA', 'MEDIUM', 'Hash Maps',
 'Explain and implement a method that returns the first non-repeating character in a string.',
 'CODING', 'Java', 'class Solution { public char solve(String value) { return 0; } }',
 'char solve(String value)', '{"cases": [{"input": "\"swiss\"", "output": "\"w\""}]}',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000003', 'DSA', 'HARD', 'Graphs',
 'Design an algorithm to find the shortest path in a weighted graph with non-negative edges.',
 'CODING', 'Java', 'class Solution { public int[] shortestPath(int[][] edges, int vertices, int source) { return new int[0]; } }',
 'int[] shortestPath(int[][] edges, int vertices, int source)',
 '{"cases": [{"input": "graph", "output": "distances"}]}',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000004', 'OOP', 'EASY', 'Encapsulation',
 'Explain encapsulation and give an example of protecting an object invariant.',
 'NON_CODING', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000005', 'OOP', 'MEDIUM', 'Design Patterns',
 'When would you choose composition over inheritance? Explain the trade-offs.',
 'NON_CODING', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000006', 'OOP', 'HARD', 'Concurrency',
 'Design a thread-safe in-memory component and explain its consistency guarantees.',
 'NON_CODING', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000007', 'JAVA', 'EASY', 'Collections',
 'What is the difference between ArrayList and LinkedList, and when would you use each?',
 'NON_CODING', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000008', 'JAVA', 'MEDIUM', 'Streams',
 'Write a Java Stream pipeline that groups orders by customer and sums their totals.',
 'CODING', 'Java', 'class Solution { public Map<String, Integer> totals(List<Order> orders) { return Map.of(); } }',
 'Map<String, Integer> totals(List<Order> orders)',
 '{"cases": [{"input": "orders", "output": "totals by customer"}]}',
 CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('70000000-0000-0000-0000-000000000009', 'JAVA', 'HARD', 'JVM',
 'Explain how garbage collection affects latency and how you would investigate a pause.',
 'NON_CODING', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;
